### ISSUE TITLE
RoadMap to v0.6

### ISSUE THREAD

**Issue by coolaj86** [dashhive/wallet.js#37]
- [x] Split change into denominations
- [x] Send denominated
- [x] Mark accounts as reserved (send into `@savings`)
- [x] Specific config dir for local dev
