### ISSUE TITLE
Roadmap to v0.7

### ISSUE THREAD

**Issue by coolaj86** [dashhive/wallet.js#45]
- [ ] `dashwallet export <addr-or-handle>`
  - [ ] QR
- [ ] Clarify usage / use case
- [ ] testnet? #33 
- [ ] Batch mode w/ Insight #13 
- [ ] Mark coins as reserved
- [ ] Uses system emailer? Generate and consume links?
- [ ] Set target denominations #14 
- [ ] Offline-ish: mark coins for check and retry on double spend
- [ ] Offline mode
- [ ] `dashwallet recover <./recovery-phrase.txt>` #12 
- [ ] config options: #32 
   ```text
   dashwallet set <config> <val>
   dashwallet get <config>
   ```
- [ ] Encrypted storage
- [ ] Browser test
- [ ] Consistent use of terms like `create` (sync) and `generate` or `assign`(?) (async)

```text
- like git has "commitish", dash CLIs should have "keyish" or "addressish"

- friend => connect, contact, meet, link
- convert to bin/_cli.js
- specify which wallet to import a wif to?
  - TODO set staletime = Infinity for --offline?
- zoomonic hd accounts & keys
- --offline - spend coins we know we have
  console.info(
    `    --mask                        hide amounts and addresses (demo mode)`,
  );
```
